version: '3'
services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      - ARANGO_NO_AUTH=1
#      - ARANGO_ROOT_PASSWORD=password
#      - ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=2G
#      - ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES=2
    ports:
      - "8529:8529"
    volumes:
      - ./data:/var/lib/arangodb3
